# Configurations so that Spring Data can connect to the application's DB correctly
api:
  security:
    token:
      secret: ${JWT_SECRET}

server:
  error:
    include-stacktrace: never

spring:
  jpa:
    # Displays DB queries and formats queries
    show-sql: true
    properties.hibernate.format_sql: true

  datasource:
    # If Spring Boot doesn't automatically find the MySQL driver in the project
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Provides the DB connection URL
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}
    # Informs the DB user
    username: ${DB_USER}
    # Informs the DB password
    password: ${DB_PASSWORD}

